### ISSUE TITLE
Content type

### ISSUE THREAD

**Issue by davidjamesstone** [fhemberger/catbox-s3#51]
Hi there,

Looking through the code I think I spotted a bug.
I'll submit a PR later but I just wanted to check with you first.

https://github.com/fhemberger/catbox-s3/blob/master/lib/index.js#L203

```js
if (['Object', 'Array'].indexOf(value.constructor.name) === 0) {
```

Should this not be:

```js
if (['Object', 'Array'].indexOf(value.constructor.name) > -1) {
```

Similarly on line 214.

Another issue I noticed during testing:

https://github.com/fhemberger/catbox-s3/blob/master/lib/index.js#L158

```js
url      : baseUrl + this.settings.bucket + '/' + internals.getStoragePathForKey(key),
```

I think the `internals.getStoragePathForKey(key)` needs encodeURIComponent.

Consider:

https://s3-eu-west-1.amazonaws.com/XXX/#getStationData/5107:u
vs
https://s3-eu-west-1.amazonaws.com/XXX/%23getStationData/5107%3Au

Other things I plan to work on but wanted to check first if you see any issues:
- Allow the bucket private (currently get assumes public-read)
- Replace `request` with `wreck` to keep within the hapi ecosystem.

Hope you can help.

Many thanks

Dave

**Comment by fhemberger** [comment]
Hi David,

yes, you're right. Thanks for pointing this out! The bucket needs to be public-read at the moment, because I'm using a direct HTTP request instead of the API method to fetch the object. But it should be ok to change. I don't have any objections to use `wreck` as well.

**Comment by fhemberger** [comment]
Fixed the issues and I'd happily accept pull requests for your other suggested changes. :+1:

**Comment by davidjamesstone** [comment]
Hi Frederic

thanks for your response.

I hope to get some time one evening this week to fork and make the changes suggested around wreck and enabling private buckets.

In the meantime, I think there's still an issue. Looking at the code.

If I pass the test

```js
if (['Object', 'Array'].indexOf(value.constructor.name) > -1) {
```
then I end up in the json.stringify try/catch. Fine but then `value` becomes a string which mean I'll then pass the test (because now, value.constructor.name === 'String'):

```js
    if (['String', 'Number', 'Boolean'].indexOf(value.constructor.name) > -1) {
        type = 'text/plain';
    } 
```

Which results is the type being redefined to 'text/plain' - not what you want.

I've submitted a [PR](https://github.com/fhemberger/catbox-s3/pull/52) for this. Hope this helps.

Dave
